SceneTag/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +[
    path('SceneTag/', include('SceneTagSite.urls')),
    path('admin/', admin.site.urls),
]

SceneTagSite/urls.py
from django.urls import path, include
from django.contrib import admin

from SceneTagSite import views

urlpatterns = [
    # video list page
    path('list/page/<list_page>/', views.video_list, name='list'),
    path('list/refresh/', views.video_list_refresh, name='refresh_list'),

    # frame_list
    path('frame/<video_id>/', views.key_frame_list, name='frame_list'),
    path('frame/<video_id>/page/<page_num>/', views.update_frames, name='frame_update'),

    # get_img
    path('extract_current_frame/', views.extract_current_frame, name='extract_current_frame'),
    path('ajax/get_frame/', views.ajax_get_frame_url, name='ajax_get_frame'),
    path('utils/image/', views.ajax_get_frame_url, name='util_media_image'),

    # object tagging
    path('tag/<video_id>/<frame_id>/', views.object_tagging, name='object_tagging'),
    path('tag/<video_id>/<frame_id>/', views.object_tagging, name='next_object_tagging'),
    path('tag/<video_id>/<frame_id>/', views.object_tagging, name='prev_object_tagging'),
    path('tag/delete/<video_id>/<tag_pk>/', views.del_object_tagging, name='del_object_tagging'),

    # auto tagging
    path('<video_id>/auto_tag/<frame_id>/json', views.object_tag_info_json, name='object_tag_json'),
    path('<video_id>/auto_tag/<frame_id>/', views.auto_object_tagging, name='auto_object_tagging'),
    path('<video_id>/auto_tag/<frame_id>/register/', views.auto_object_tagging_register, name='auto_object_tagging_register'),
    path('<video_id>/auto_tag/<frame_id>/modify/', views.auto_object_tagging_modify, name='auto_object_tagging_modify'),
    path('<video_id>/auto_tag/<frame_id>/bbox/', views.bbox, name='bbox'),

    # csv
    path('export/<video_id>/object/csv/', views.export_object_tag_csv, name='export_object_tag_csv'),
    path('export/<video_id>/event/json/', views.export_event_tag_json, name='export_event_tag_json'),

    # ajax
    path('ajax/get_data/', views.get_data, name='api-data'),
    path('ajax/bbox_data/', views.bbox, name='bbox'),

    # interval_video_list
    path('interval/<video_id>/', views.IntervalVideoBrowse.as_view(), name='interval_video_list'),
    path('interval/<video_id>/page/<page_num>', views.update_interval_video, name='update_interval'),
    path('making_interval_video/', views.making_interval_video, name='making_interval_video'),
    path('interval/delete/<video_id>/<interval_pk>/', views.delete_interval_video, name='delete_interval_video'),
    path('interval_tag/<video_id>/<interval_pk>/register/', views.interval_video_tagging_register, name='interval_video_tagging_register'),
]

SceneTagSite/models.py
from __future__ import unicode_literals

import ast
from django.conf import settings
from django.db import models
from django.utils import timezone
from SceneTagSite.utils.converter import TimeConverter
from SceneTagSite.utils.choices import *
from SceneTagSite import tasks


class Video(models.Model):
    programName = models.CharField(max_length=255)
    localFile = models.FileField(blank=True)
    registerDateTime = models.DateTimeField(default=timezone.now)
    lastSavedDateTime = models.DateTimeField(default=timezone.now)
    pgm_tms_id = models.CharField(max_length=255, default=0)
    framerate = models.FloatField(default=29.97)
    width = models.IntegerField(default=0)
    height = models.IntegerField(default=0)
    frame_count = models.IntegerField(default=0)
    length = models.CharField(max_length=100, default="")

    def __unicode__(self):
        return self.programName

    def save(self, *args, **kwargs):
        self.lastSavedDateTime = timezone.now()
        super(Video, self).save(*args, **kwargs)


class FrameList(models.Model):
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    start_frame = models.IntegerField(default=0)
    end_frame = models.IntegerField(default=0)
    imgName = models.CharField(max_length=255, null=True)
    framerate = models.FloatField(default=29.97)
    currentFrame = models.IntegerField(default=0)
    currentTimeStamp = models.CharField(max_length=255, blank=True)

    def make_timestamp(self, frame, framerate):
        tc = TimeConverter(frame_rate=framerate)
        tc.set_framenum(frame)
        return tc.get_timestamp()

    def save(self, *args, **kwargs):
        self.currentTimeStamp = self.make_timestamp(frame=self.currentFrame, framerate=self.framerate)
        super(FrameList, self).save(*args, **kwargs)

    def __unicode__(self):
        name = u'frame_pk:' + str(self.pk)
        return name


class ObjectTag(models.Model):
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    frame = models.ForeignKey(FrameList, on_delete=models.CASCADE, null=True)
    currenttime = models.CharField(max_length=255, blank=True)
    imgName = models.CharField(max_length=255)
    imgWidth = models.IntegerField(default=0)
    imgHeight = models.IntegerField(default=0)
    x1 = models.IntegerField(default=0)
    y1 = models.IntegerField(default=0)
    w = models.IntegerField(default=0)
    h = models.IntegerField(default=0)
    label = models.IntegerField(choices=OBJECT_CHOICES, default=0)
    lastSavedDateTime = models.DateTimeField(default=timezone.now)

    def __unicode__(self):
        name = u'Object_pk:' + str(self.pk)
        return name

    def save(self, *args, **kwargs):
        super(ObjectTag, self).save(*args, **kwargs)


class AutoObjectTag(models.Model):
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    frame = models.ForeignKey(FrameList, on_delete=models.CASCADE)
    module_name = models.TextField(blank=True)
    test = models.TextField(blank=True)
    x = models.FloatField(null=True, unique=False)
    y = models.FloatField(null=True, unique=False)
    w = models.FloatField(null=True, unique=False)
    h = models.FloatField(null=True, unique=False)
    threshold = models.FloatField(default=0)

    def __unicode__(self):
        name = u'AutoObjectTag_pk :' + str(self.pk)
        return name

    def save(self, *args, **kwargs):
        super(AutoObjectTag, self).save(*args, **kwargs)
        self.test = str(tasks.communicator("http://mlcoconut.sogang.ac.kr:8000/analyzer/", self.frame,
                                           modules=self.module_name))

        json_data = ast.literal_eval(self.test)
        for modules_results in json_data:
            self.values = str(modules_results)
            json_data_position = ast.literal_eval(self.values)
            self.module_name = json_data_position['module_name']  # module상에서
            for module_results in json_data_position['module_result']:
                self.y = module_results['position']['y']
                self.h = module_results['position']['h']
                self.w = module_results['position']['w']
                self.x = module_results['position']['x']
                self.values = str(module_results['label'])
                json_data_label = ast.literal_eval(self.values)
                for labels in json_data_label:
                    temp_int = round(float(labels['score']), 2)
                    if temp_int >= self.threshold:
                        self.auto_tag.create(auto_description=labels['description'], auto_score=temp_int,
                                             auto_module_name=self.module_name, x=self.x, y=self.y, w=self.w,
                                             h=self.h)
        super(AutoObjectTag, self).save()


class AutoTagResult(models.Model):
    auto_tag_result = models.ForeignKey(AutoObjectTag, related_name='auto_tag', on_delete=models.CASCADE)
    auto_module_name = models.TextField(blank=True)
    auto_description = models.TextField(null=True, unique=False)
    auto_score = models.FloatField(null=True, unique=False)
    x = models.FloatField(null=True, unique=False)
    y = models.FloatField(null=True, unique=False)
    w = models.FloatField(null=True, unique=False)
    h = models.FloatField(null=True, unique=False)

    def __unicode__(self):
        name = u'AutoTagResult_pk :' + str(self.pk)
        return name


def make_new_interval_video(video_pk, start_frame, end_frame, start_timestamp, end_timestamp):
    video = Video.objects.get(pk=video_pk)
    new_interval_video = IntervalVideo(video=video)
    new_interval_video.startFrame = start_frame
    new_interval_video.endFrame = end_frame
    new_interval_video.startTimestamp = start_timestamp
    new_interval_video.endTimestamp = end_timestamp
    new_interval_video.save()


class IntervalVideo(models.Model):
    video = models.ForeignKey(Video, on_delete=models.CASCADE,null=True)
    startFrame = models.IntegerField(default=0)
    endFrame = models.IntegerField(default=0)
    startTimestamp = models.CharField(max_length=255, blank=True)
    endTimestamp = models.CharField(max_length=255, blank=True)
    tag1 = models.IntegerField(choices=INTERVAL_CHOICES, default=0)
    tag2 = models.IntegerField(choices=INTERVAL_CHOICES, default=0)
    tag3 = models.IntegerField(choices=INTERVAL_CHOICES, default=0)

    def __unicode__(self):
        name = str(self.video.programName) + \
               u'IntervalVideo('+str(self.pk)+u')'
        return name


SceneTagSite/forms.py
from django import forms
from .models import ObjectTag, AutoObjectTag, AutoTagResult, IntervalVideo


class ObjectTagForm(forms.ModelForm):
    class Meta:
        model = ObjectTag
        fields = ('x1', 'y1', 'w', 'h', 'label')


class ObjectTaggingForm(forms.ModelForm):
    class Meta:
        model = AutoObjectTag
        fields = ('video', 'frame', 'threshold', 'module_name')


class ResultTagForm(forms.ModelForm):
    class Meta:
        model = AutoTagResult
        fields = ('auto_module_name', 'auto_description', 'auto_score')


class IntervalTagForm(forms.ModelForm):
    class Meta:
        model = IntervalVideo
        fields = ('tag1','tag2', 'tag3')


templates/SceneTagSite/auto_tagging.html
{%  extends 'SceneTagSite/base.html' %}
{%  load static %}
{% load base_tags %}

{% block head %}
{% endblock head %}

{% block nav %}
    {% nav_bar %}
{% endblock nav %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12" align="center">
                <div class="card">
                    <div class="card-header">
                         <div class="col" style="font-size: 28px;text-align: center" >
                            <a id="previous_btn" href="{% url "auto_object_tagging" video.pk prev_url %}"><i class="far fa-arrow-alt-circle-left"></i></a>
                                <strong>Auto Object Tagging</strong>
                            <a id="next_btn" href="{% url "auto_object_tagging" video.pk next_url %}"><i class="far fa-arrow-alt-circle-right"></i></a>
                         </div>
                    </div>
                    <br>
                    <a href="{% url 'object_tag_json' video.pk frame.pk %}" class="btn btn-info btn-block">Get JSON</a>
                    <br>
                    <div class="card-body ">
                        <img id = "target" src="{{ img_url }}" style="width: 724px; height: 408px;">
                    </div>
                </div>
            </div>
        </div>
        <br>

        <div id="exampleAccordion" data-children=".item">
            <div class="row">
                <div class="item col-md-4 card" style="text-align: center">
                    <a data-toggle="collapse" data-parent="#exampleAccordion" href="#exampleAccordion1" aria-expanded="true" aria-controls="exampleAccordion1">
                        <h4 class="card-header">장소</h4>
                    </a>
                    <div id="exampleAccordion1" class="collapse show" role="tabpanel">
                        <p>
                            <br>
                            {% for tag in object_tag_result_place %}
{#                                {{ tag }}<br>#}
                                {{ tag|join:": "  }}<br>
                            {% endfor %}

                            {#                            {% for label_tag in label_scene_tag_result %}#}
                            {#                                {{ label_tag.get_scene_description_first_display }}<br>#}
                            {#                                {{ label_tag.get_scene_description_second_display }}<br>#}
                            {#                                {{ label_tag.get_scene_description_third_display }}<br><br>#}
                            {#                                <a href="{% url 'edit_scene_tag_form' video.pk scene.pk %}">수동 태그 수정<i class="fas fa-edit"></i></a>#}
                            {#                            {% endfor %}#}
                            {##}
                            {#                            {% if not label_scene_tag_result %}#}
                            {#                                <a href="{% url 'scene_tag_register' video.pk scene.pk %}">수동 태그 등록 <i class="fas fa-tags"></i></a><br><br>#}
                            {#                            {% endif %}#}
                        </p>
                    </div>
                </div>

                <div class="item col-md-4 card" style="text-align: center">
                    <a data-toggle="collapse" data-parent="#exampleAccordion" href="#exampleAccordion2" aria-expanded="false" aria-controls="exampleAccordion2">
                        <h4 class="card-header">객체</h4>
                    </a>
                    <div id="exampleAccordion2" class="collapse show" role="tabpanel">
                        <p class="mb-3"><br>
                            {% for tag in object_tag_result_object %}
                                {{ tag|join:": "  }} <br>
                            {% endfor %}
                        </p>
                    </div>
                </div>

                <div class="item col-md-4 card " style="text-align: center;">
                    <a data-toggle="collapse" data-parent="#exampleAccordion" href="#exampleAccordion3" aria-expanded="false" aria-controls="exampleAccordion3">
                        <h4 class="card-header">인물</h4>
                    </a>
                    <div id="exampleAccordion3" class="collapse show" role="tabpanel"><br>
                        <p class="mb-3">
                            {% for tag in object_tag_result_face %}
                                {{ tag|join:": "  }} <br>
                            {% endfor %}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <a href="{% url 'bbox' video.pk frame.pk %}" class="btn btn-info btn-block">태그 상세</a>
    <br>
    <a href="{% url 'auto_object_tagging_register' video.pk frame.pk %}" class="btn btn-success btn-block">태그 등록</a>
    <br>
    <a href="{% url 'auto_object_tagging_modify' video.pk frame.pk %}" class="btn btn-primary btn-block">태그 수정</a>
{% endblock content %}

{% block jquery %}
       <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
{% endblock jquery %}

templates/SceneTagSite/auto_tagging_modify.html
{% extends 'SceneTagSite/base.html' %}
{%  load static %}
{% load base_tags %}

{% block head %}
    <link href="{% static "css/tag_form_styles.css" %}" rel="stylesheet">
{% endblock head %}

{% block nav %}
    {% nav_bar %}
{% endblock nav %}

{% block content %}
      <div class="col" style="font-size: 28px;text-align: center" >
        <strong>태그 수정</strong>
    </div><br>
    <form method="post" novalidate>{% csrf_token %}
        {{ formset.management_form }}

        <table class="table table-borderless">
            <thead>
            <tr>
                <th scope="col">module name</th>
                <th scope="col">수정할 tag</th>
                <th scope="col">score</th>
            </tr>
            </thead>
            <tbody>
            {%  for form in formset %}
                {{ form.id }}
                <tr>
                    {% if forloop %}
                        {% for field in form.auto_module_name %}
                            <td>{{ field }}<br></td>
                        {% endfor %}
                        {% for field in form.auto_description %}
                            <td>{{ field }}</td>
                        {% endfor %}
                        {% for field in form.auto_score %}
                            <td>{{ field }}</td>
                        {% endfor %}
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <div class="col-md-12" align="right">
            <button type="submit" class="save btn btn-success btn-block">Save</button>
        </div>

    </form>
{% endblock content %}

templates/SceneTagSite/auto_tagging_register.html
{% extends 'SceneTagSite/base.html' %}
{%  load static %}
{% load base_tags %}

{% block head %}
{% endblock head %}

{% block nav %}
    {% nav_bar %}
{% endblock nav %}

{% block content %}
    <div class="alert alert-success" role="alert">
        비디오 정보 : {{ video.programName }}<br>
    </div>

    <br>
    <form method="POST" class="post-form">{% csrf_token %}
        <p>
            <label for="id_video">Video</label>
            <select name="video" class="browser-default custom-select mb-4" required id="id_video" placeholder="Disabled input">
                <option value="{{ video.id }}">{{ video.programName }}</option>
            </select>
        </p>

        <p>
            <label for="id_frame">Frame</label>
            <select name="frame" class="browser-default custom-select mb-4" required id="id_frame" placeholder="Disabled input">
                <option value="{{ frame.id }}">{{ frame }}</option>
            </select>
        </p>

        <p>
            <label for="id_threshold">Threshold</label>
            <select name="threshold" class="browser-default custom-select mb-4" required id="id_threshold">
                <option>0</option>
                <option>0.1</option>
                <option>0.2</option>
                <option>0.3</option>
                <option>0.4</option>
                <option>0.5</option>
                <option>0.6</option>
                <option>0.7</option>
                <option>0.8</option>
                <option>0.9</option>
            </select>
        </p>

        <p>
            <label for="id_module_name">Module Name</label>
            <select name="module_name" class="browser-default custom-select mb-4" required id="id_module_name">
                <option>korea.place</option>
                <option>object</option>
                <option>korea.face</option>
            </select>
        </p>


        <div class="col-md-12" align="right">
            <button type="submit" class="save btn btn-success">태그등록</button>
        </div>
    </form>
{% endblock content %}

templates/SceneTagSite/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <link rel="icon" type="image/png" href="http://example.com/myicon.png">

    <title>SceneTag</title>

      <link href="https://vjs.zencdn.net/7.6.5/video-js.css" rel="stylesheet">

      <!-- If you'd like to support IE8 (for Video.js versions prior to v7) -->
      <script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>

    {% block head %}
    {% endblock %}
</head>

<body>
{% block nav %}
{% endblock %}

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

   <!-- video js-->
    <script src='https://vjs.zencdn.net/7.6.5/video.js'></script>

    <!-- Custom Styles for this template-->
    <link href="{% static "css/navbar.css"%}" rel="stylesheet">

{% block jquery %}
{% endblock %}
</body>


</html> 

templates/SceneTagSite/edit_video.html
{% extends 'SceneTagSite/base.html' %}
{% load static %}


{% block head %}
{% endblock head %}

{% block content %}

    <strong>{{ video.programName }}</strong><br>
    <div id="playerWrapper" align="center">
        <video class="video-js vjs-default-skin vjs-big-play-centered" id="video_id" controls preload="auto" data-setup="{}">
            <source src="{{ video.localFile.url }}" type="video/mp4">
        </video>
    </div><br>




    <strong>Frame List</strong><br>
    <table id="shotWrapper" class="table table-striped">
        <thead id="table-header" align="center">
        <th class="row">
            <div class="col-md-3" align="center">Frame</div>
            <div class="col-md-3" align="center">Current Time Stamp</div>
            <div class="col-md-2" align="center">Current Frame</div>
            <div class="col-md-4" align="center">Grouping</div>
        </th>
        </thead>

    </table>


    {% for frame in  frames %}
        <div class="row" id={{ frame.pk }} align="center">
            <div  class="col-md-3">
                <img class="img-thumbnail" id="frame{{ frame.currentFrame }}" src="...">
            </div >
            <div  class="col-md-3">
                {{ frame.currentTimeStamp }}
            </div >
            <div  class="col-md-2">
                frame_{{ frame.currentFrame }}
            </div >
            <div  class="col-md-4">

            </div >
        </div >
    {% endfor %}



{% endblock content %}

{% block jquery %}

{% endblock jquery %}

templates/SceneTagSite/interval_tagging_register.html
{%  extends 'SceneTagSite/base.html' %}
{%  load static %}
{% load base_tags %}

{% block head %}
{% endblock head %}

{% block nav %}
    {% nav_bar %}
{% endblock nav %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12" align="center">
                <div class="card">
                    <div class="card-header">
                         <div class="col" style="font-size: 28px;text-align: center" >
                            <a id="delete_previous_scene_btn" href="{% url "interval_video_tagging_register" video.pk prev_url %}"><i class="far fa-arrow-alt-circle-left"></i></a>
                                <strong>Interval Video Tagging</strong>
                            <a id="delete_next_scene_btn" href="{% url "interval_video_tagging_register" video.pk next_url %}"><i class="far fa-arrow-alt-circle-right"></i></a>
                         </div>
                    </div>
                    <br>
                    <div id="playerWrapper" align="center">
                        <video class="video-js vjs-default-skin vjs-big-play-centered" id="video_id" controls preload="auto" width="720" height="360" data-setup="{}">
                            <source src="{{ video.localFile.url }}" type="video/mp4">
                        </video>
                    </div>
                    <br>
                </div>
            </div>
        </div>
        <br>
        <div class="alert alert-success" role="alert">
            <strong>비디오 정보 --- {{ video.programName }}</strong><br>
        </div>
        <div class="alert alert-success" role="alert">
            <strong>구간 ---</strong> <strong id="show_start"></strong> ~ <strong id="show_end"></strong> <i onclick="playback(startTime='{{ interval.startTimestamp }}', endTime='{{ interval.endTimestamp }}');" id="play_scene", class="far fa-caret-square-right fa-1x" style="cursor:pointer"></i><br>
        </div>
        <div class="alert alert-success" role="alert">
            <strong>Tag 내용 ---</strong> <strong id="tag_list"> {{ interval.get_tag1_display }} | {{ interval.get_tag2_display }} | {{ interval.get_tag3_display }} </strong> <br>
         </div>

        <form method="POST" class="post-form">{% csrf_token %}

            <div class="inline_label" align="center">
                <label for="id_tag1">
                    <strong>Tag1</strong>
                    <select name="tag1" class="browser-default custom-select mb-2" required id="id_tag1">
                        {% for choice in form.tag1.field.choices %}
                            <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                        {% endfor %}
                    </select>
                </label>
                 <label for="id_tag2">
                    <strong>Tag2</strong>
                    <select name="tag2" class="browser-default custom-select mb-2" required id="id_tag2">
                        {% for choice in form.tag2.field.choices %}
                            <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                        {% endfor %}
                    </select>
                </label>
                 <label for="id_tag3">
                    <strong>Tag3</strong>
                    <select name="tag3" class="browser-default custom-select mb-2" required id="id_tag3">
                        {% for choice in form.tag3.field.choices %}
                            <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                        {% endfor %}
                    </select>
                </label>

                <select name="video" class="browser-default custom-select mb-4" required id="id_video" placeholder="Disabled input" style="display: none" >
                    <option value="{{ video.id }}">{{ video }}</option>
                </select>
                <input name="startFrame" type="hidden" class="browser-default custom-select mb-2" required id="id_startFrame" value="{{ interval.startFrame }}">
                <input name="endFrame" type="hidden" class="browser-default custom-select mb-2" required id="id_endFrame" value="{{ interval.endFrame }}">
                <input name="startTimestamp" type="hidden" class="browser-default custom-select mb-2" required id="id_startTimestamp" value="{{ interval.startTimestamp }}">
                <input name="endTimestamp" type="hidden" class="browser-default custom-select mb-2" required id="id_endTimestamp" value="{{ interval.endTimestamp }}">
            </div>


            <div class="col-md-12" align="right">
                <button type="submit" class="save btn btn-success">태그등록</button>
            </div>
        </form>
    </div>


{% endblock content %}

{% block jquery %}
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static "js/playback.js" %}"></script>
    <script>
        document.getElementById("show_start").innerHTML = timeFormat({{ interval.startTimestamp }});
        document.getElementById("show_end").innerHTML = timeFormat({{ interval.endTimestamp }});
    </script>

{% endblock jquery %}


templates/SceneTagSite/nav_bar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="container">

        <a class="navbar-brand" href="#">CCTV Tagging</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbars" aria-controls="navbars" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbars">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'list' 1 %}">
                        <span class="fas fa-list-ul"></span>
                        VideoList
                        <span class="sr-only">(current)</span></a>
                </li>
                {% if video %}
                    <li class="nav-item">
                        <a class="nav-link text-success">
                            <span class="fas fa-eye"></span>
                            {{ video.programName }}
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>

templates/SceneTagSite/taggingchart.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Event Drops</title>
</head>
<body>
    <h1>Event Drops Demo</h1>
        <div id="eventdrops-demo" style="width: 90%;"></div>
        <p class="infos">
            <span id="zoomStart"></span> <span class="light"></span> <span id="zoomEnd"></span>
        </p>
</body>
</html>
<script>

</script>

templates/SceneTagSite/util_image_ajax.html
<script>
    function setURL2ImageTag(data) {
        console.log("Set Image"+data[0]['URL']+"to"+data[0]['tagID']);
        $(data[0]['tagID']).attr('src',data[0]['URL']);
    }
    function getImageURL(tagID, videoPK, frameNum){
        $.ajax({
            url : '{% url 'ajax_get_frame' %}',
            data : {
                videoNum: videoPK,
                name : 'getFrameURL',
                frameNum: frameNum,
                tagID: tagID,
            },
            success: setURL2ImageTag,
        });
    }
</script>